run_scenario:
  target:
    entity:
      integration: energy_engine
      domain: sensor
  fields:
    period:
      required: true
      selector:
        select:
          mode: dropdown
          translation_key: lookback_period
          options:
            - today
            - week
            - month
            - three_months
            - six_months
            - year

run_comparison:
  target:
    entity:
      integration: energy_engine
      domain: sensor
  fields:
    period:
      required: true
      selector:
        select:
          mode: dropdown
          translation_key: lookback_period
          options:
            - today
            - week
            - month
            - three_months
            - six_months
            - year

verify_entities:
  target:
    device:
      integration: energy_engine
  fields:
    period:
      required: true
      selector:
        select:
          mode: dropdown
          translation_key: lookback_period
          options:
            - today
            - week
            - month
            - three_months
            - six_months
            - year
