run_scenario:
  target:
    entity:
      integration: energy_engine
      domain: sensor
  fields:
    start_date:
      required: true
      selector:
        date: {}
    end_date:
      required: true
      selector:
        date: {}

run_comparison:
  target:
    entity:
      integration: energy_engine
      domain: sensor
  fields:
    start_date:
      required: true
      selector:
        date: {}
    end_date:
      required: true
      selector:
        date: {}

verify_entities:
  target:
    device:
      integration: energy_engine
  fields:
    start_date:
      required: true
      selector:
        date: {}
    end_date:
      required: true
      selector:
        date: {}
